# Rest
server:
  port: ${SERVER_PORT:8091}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com:
      pichincha:
        customer: ${LOG_LEVEL:INFO}

spring:
  application:
    name: cde-msa-bp-async-customer

  datasource:
    url: jdbc:postgresql://localhost:5432/BDD_BANK_DEV
    username: postgres
    password: frankys82
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest